# fly.toml app configuration file generated for exercises-dark-butterfly-8071 on 2024-10-15T13:39:32-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'exercises-dark-butterfly-8071'
primary_region = 'den'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
